apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "handshake-hsd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "handshake-hsd.name" . }}
    helm.sh/chart: {{ include "handshake-hsd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "handshake-hsd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "handshake-hsd.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["hsd"]
          args:
          - "--rs-host"
          - "0.0.0.0"
          - "--rs-port"
          - "{{ .Values.service.rsPort }}"
          - "--ns-port"
          - "{{ .Values.service.nsPort }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
          ports:
            - name: rs
              containerPort: {{ .Values.service.rsPort }}
            - name: ns
              containerPort: {{ .Values.service.nsPort }}
            - name: p2p
              containerPort: {{ .Values.service.p2pPort }}
          volumeMounts:
          - name: data
            mountPath: /root/.hsd
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "handshake-hsd.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
