apiVersion: v1
kind: Service
metadata:
  name: {{ include "handshake-hsd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "handshake-hsd.name" . }}
    helm.sh/chart: {{ include "handshake-hsd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
    - name: rs
      targetPort: rs
      port: {{ .Values.service.rsPort }}
    - name: ns
      targetPort: ns
      port: {{ .Values.service.nsPort }}
    - name: p2p
      targetPort: p2p
      port: {{ .Values.service.p2pPort }}
  selector:
    app.kubernetes.io/name: {{ include "handshake-hsd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
